<?php include('includes/header.php')?>
 <!--Inner Banner Start-->
     <Section class="inner_banner ">
        <div class="container_fluid">
            <div class="flex_row">
                <div class="col_8">
                    <h4>G20 Country Initiatives</h4>
                </div>
               
                <div class="col_4">
                    <ul class="new_breadcrumb">
                        <li><a href="<?php echo $base_url; ?>">Home</a></li>
                        <li>G20 Country Initiatives</li>
                    </ul>
                </div>
            </div>
        </div>
    </Section>
    <!--Inner Banner End-->
    <!--First Section Start-->
    <section class="common_spacing">
        <div class="container_fluid">
            <div class="sidebar_sticky_wrapper">
                <div class="sidebar_sticky_left">
                    <ul class="vertical_tabs"> 
                        <li><a href="g20_country_initiatives.php#CI_policy_progam" class="active"><span>Policy and Programs</span> <i class="icon-play"></i></a></li> 
                        <li><a href="g20_country_initiatives.php#CI_good_practice"><span>Good Practices</span> <i class="icon-play"></i></a></li>
                        <li><a href="g20_country_initiatives.php#CI_traditional_indigenous"><span>Traditional / Indigenous knowledge</span> <i class="icon-play"></i></a></li>
                        <li><a href="g20_country_initiatives.php#CI_design_framework"><span>Design Frameworks</span> <i class="icon-play"></i></a></li> 
                        <li><a href="g20_country_initiatives.php#CI_knowledge_Resources"><span>Knowledge Resources</span> <i class="icon-play"></i></a></li> 
                        <li><a href="g20_country_initiatives.php#CI_social_media"><span>Social Media Links</span> <i class="icon-play"></i></a></li> 
                        <li><a href="g20_country_initiatives.php#CI_financing_for_land_conservation_restoration"><span>Financing for Land Conservation and Restoration</span> <i class="icon-play"></i></a></li>
                        <li><a href="g20_country_initiatives.php#CI_news_events"><span>National Events and News</span> <i class="icon-play"></i></a></li>
                    </ul>
                </div>

                <div class="sidebar_sticky_right">
                    <!-- Policy and Program start here -->
                    <div class="country_initiative_topic_wrapper" id="CI_policy_progam">
                        <div class="flex_row">
                            <div class="col_10">
                                 <h2>Knowledge Resources</h2>
                            </div>
                            <div class="col_2">
                            <button class="back_btn"><a href="g20_country_initiatives.php#CI_knowledge_Resources" class="">Back</a></button>
                            </div>
                        </div>
                        <div class="flex_row">
                            <div class="col_12">
                            <h5>Mine Reclamation: A handbook, Indian Council of Forestry and Research Education</h5>
                                <p>
                                    Minerals and mining sector contributes significantly to the economic growth and development of 
                                    India in the form of exports, raw material to other industries in the country and finally vast 
                                    employment opportunities and a high rate of wages. The Indian mining industry currently employs 
                                    over 1.1 million people. Mining also yields foreign exchange and accounts for a significant 
                                    portion of gross domestic product. Thus, the economic opportunities and wealth generated by
                                     mining for the country are substantial. However, mining is associated with severely adverse 
                                     effects on the environment including loss of biodiversity, erosion, contamination of surface 
                                     water, ground water, and soil. Mining causes physical destruction to the surrounding land by 
                                     creating landscape blots such as open pits and piles of waste rock. Such disruptions result in 
                                     the deterioration of the area's flora and fauna. In most of the cases the surface features and 
                                     vegetation that were present before mining activities cannot be replaced after the process has 
                                     ended. Loss of soil productivity, biological diversity, health and environmental hazards due to 
                                     air, water and noise pollution microclimatic changes etc. are the major problems of the mining 
                                     process. Reclamation on mined areas thus pose a great challenge for ecologists, biologists, 
                                     agriculturists, engineers, soil scientist, and foresters as well who are invariably concerned 
                                     about restoration of this disturbed ecosystem. Therefore, Indian Council of Forestry Research 
                                     and Education has come up this operational manual incorporating comprehensive information on 
                                     various aspects of mine reclamation including extent and causes of land degradation, scope and 
                                     reclamation scenario in India, approaches and strategies of reclamation of mine spoils, essentials 
                                     of ecofriendly mining and species prescriptions for different mining scenarios. The manual also 
                                     contains outstanding reclamation efforts of various ICFRE institutions in recent past. 
                                </p>
                               
                            </div>
                        </div>
                    </div>
                    <!-- Good Practice start here -->
                    <div class="country_initiative_topic_wrapper" id="additional_section">
                    <div class="flex_row">
                        <div class="col_12">
                        <h2>Additional Topics</h2>
                        </div>
                    </div>
                        <div class="flex_row">
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>compendium of Best Practices on restoration of Mining Affected Areas</h5>
                                        <p>
                                        Mineral resources are the backbone of the economy. Mining is a significant contributor to the development of many countries around the world, many developing and emerging economies, and developed...
                                        </p>
                                        <a href="g20_country_initiatives_knowledge_resources_mining_compendium_best_practices.php">Read More</a>
                                        <!--Pdf Section Start-->
                                        <div class="pdf_document">
                                            <a href="assets/pdf/G20_ECSWG-Compendium_Best_Practices_on_Restoration_of_Mining_Affected_Areas.pdf" target="_blank">
                                                <img src="assets/images/pdf_icon.webp" class="pdf_icon">
                                                <span>G20 ECSWG Compendium Best Practices on Restoration of Mining Affected Areas.pdf</span>
                                            </a>
                                        </div>
                                        <!--Pdf Section End-->
                                    </div>
                                </div>
                            </div>
                            <!--Second Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Eco Friendly Approaches for Rehabilitation of Mine Spoils, Institute of Forest Genetics and Tree Breeding</h5>
                                        <p>
                                            After Forest conservation Act 1980 nearly 1.50 was diverted for mining alone. Other areas 
                                            for which forest lands were diverted include transmission lines, hydro projects, defence 
                                            and roads etc...
                                        </p>
                                        <a href="g20_country_initiatives_knowledge_resources_ecofriendly_approaches.php">Read More</a>
                                    </div>
                                </div>
                            </div>
                            <!--Third Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Developing Ecological Restoration Model In The Mine Spoils At Tetulmari Under Sijua Area 
                                        (About 8-10 Ha) Of Bccl Mine, Forest Ecology & Environment Division Forest Research Institute, 
                                        Dehradun, India
                                    </h5>
                                        <p>
                                         Almost all the mining techniques from mineral explorations to production and transport are 
                                         causing environmental damage in several ways. The list includes deforestation, loss of topsoil, 
                                         accelerated soil erosion, soil contamination, qualitative and quantitative depletion of surface 
                                         and ground water resources, migration of wild life and avian fauna, and addition of air 
                                         pollutants and dust in the atmosphere.
                                        </p>
                                        <a href="g20_country_initiatives_knowledge_resources_developing_ecological_restoration.php">Read More</a>
                                    </div>
                                </div>
                            </div>
                            <!--Fourth Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Seed Ball Technology for Restoration of Coal Mined Land, Rain Forest Research Institute, India
                                    </h5>
                                        <p>
                                            Seed ball technology is an old age technique adopted for propagating plants from seeds 
                                            throwing seeds balls without opening up soil with cultivation tools. Seed balls 
                                            (earth balls) are made by mixing seeds of different plant species...
                                        </p>
                                        <a href="g20_country_initiatives_knowledge_resources_seed_ball_technology.php">Read More</a>
                                    </div>
                                </div>
                            </div>
                            <!--Fifth Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Road Map for Ecological Restoration Works in Coal Mines of NCL, Singrauli, M.P.; Forest Research Institute, Dehradun, India
                                    </h5>
                                        <p>
                                            The various activities required for ecological restoration of coal mines have been discussed 
                                            and suggested for their implementation in the field as the part of road map...
                                        </p>
                                        <a href="g20_country_initiatives_knowledge_resources_ecological_roadmap.php">Read More</a>
                                    </div>
                                </div>
                            </div>
                            <!--Sixth Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Developing Ecological Restoration Model In The Mine Spoils At Tetulmari Under Sijua Area 
                                        (About 8-10 Ha) Of Bccl Mine, Forest Ecology & Environment Division Forest Research Institute, 
                                        Dehradun, India
                                    </h5>
                                        <p>
                                         Almost all the mining techniques from mineral explorations to production and transport are 
                                         causing environmental damage in several ways. The list includes deforestation, loss of topsoil, 
                               
                        </div>
                </div>
            </div>
        </div>
    </section>

     <!--First Section End-->
    

    <!--Second Section End-->
    <!--Footer Section Start-->
    <?php include('includes/footer.php')?>
    <!-- Footer Section End-->