<?php include('includes/header.php')?>
     <!--Breadcrumb section Start-->
     <Section class="breadcrumb ">
        <div class="container_fluid">
            <div class="flex_row">
                <div class="col_9">
                    <h2>Mining Affected Landscapes</h2>
                </div>
                <div class="col_3 breadcrumb_lnk_india_presidency">
                    <ul>
                        <li>Home</li>
                        <li>Mining Affected Landscapes</li>
                    </ul>
                </div>
            </div>
        </div>
    </Section>
    <!--Breadcrumb section End-->
    <!--First Section Start-->
    <main class=" gradient_container_image_lotus_right gradient_container_topbar_right dtls_page">
    <section class="country_initiatives ">
        <div class="container_fluid gradient_container_topbar_left  common_spacing_top_btm gradient_container_image_lotus_left">
            <div class="flex_row  gradient_container_left">
                    <div class="col_4  sidebar_navigation">
                        <div class="flex_row">
                            <div class="col_12">
                                <section class="fixme">
                                <ul class=""> 
                                    <li class="sub_menu"><a href="mining_affected_landscapes.php#policy_prgrms_section" class="active">Policy and Programs</a></li> 
                                    <li class="sub_menu"><a href="mining_affected_landscapes.php#knowledge_resources">Knowledge Resources</a></li>
                                    <li class="sub_menu"><a href="mining_affected_landscapes.php#design_framework_Section">Design Frameworks</a></li>
                                    <li class="sub_menu"><a href="mining_affected_landscapes.php#technology_tools_Section">Technology & Tools</a></li> 
                                </ul> 
                                </section>
                            </div>
                        </div>
                        <div class="flex_row">
                            <div class="col_12 ">

                            </div>                  
                        </div>
                    </div>
                <div class="col_8">
                    <!--policy_programs_section Start-->
                    <section id="policy_prgrms_section">
                        <div class="flex_row">
                            <div class="col_9">
                                <h2>Knowledge Resources</h2>
                            </div>
                            <div class="col_3">
                                <button class="back_btn"><a href="mining_affected_landscapes.php#knowledge_resources" class="">Back</a></button>
                            </div>  
                        </div>
                        <div class="flex_row">
                            <div class="col_12">
                                <h5>Training Materials </h5>
                            </div>
                            <div class="col_12"> 
                                <p>
                                <STRONG>a.	Mine Reclamation: A handbook, Indian council of Forestry and Research Education</STRONG></br>
                                Minerals and mining sector contributes significantly to the economic growth and development of India in the form of exports, raw material to other industries in the country and finally vast employment opportunities and a high rate of wages. The Indian mining industry currently employs over 1.1 million people. Mining also yields foreign exchange and accounts for a significant portion of gross domestic product. Thus, the economic opportunities and wealth generated by mining for the country are substantial. However, mining is associated with severely adverse effects on the environment including loss of biodiversity, erosion, contamination of surface water, ground water, and soil. Mining causes physical destruction to the surrounding land by creating landscape blots such as open pits and piles of waste rock. Such disruptions result in the deterioration of the area's flora and fauna. In most of the cases the surface features and vegetation that were present before mining activities cannot be replaced after the process has ended. Loss of soil productivity, biological diversity, health and environmental hazards due to air, water and noise pollution microclimatic changes etc. are the major problems of the mining process. Reclamation on mined areas thus pose a great challenge for ecologists, biologists, agriculturists, engineers, soil scientist, and foresters as well who are invariably concerned about restoration of this disturbed ecosystem. Therefore, Indian Council of Forestry Research and Education has come up this operational manual incorporating comprehensive information on various aspects of mine reclamation including extent and causes of land degradation, scope and reclamation scenario in India, approaches and strategies of reclamation of mine spoils, essentials of ecofriendly mining and species prescriptions for different mining scenarios. The manual also contains outstanding reclamation efforts of various ICFRE institutions in recent past.                              </p>
                                <!--Pdf Section Start-->
                                            <div class="flex_row pdf_box">
                                            
                                            <div class="col_1 pdf_icon_box">
                                                <a href="assets/pdf/book15.pdf.pdf" target="_blank">
                                                <img src="assets/images/pdf_icon.webp" class="pdf_icon">
                                                </a>
                                            </div>
                                            <div class="col content_center">
                                                <a href="assets/pdf/book15.pdf.pdf" target="_blank">
                                                <p><b>book15.pdf</b></p>
                                                </a>
                                            </diV>
                                                                
                                            </div>
                                        <!--Pdf Section End-->
                            </div>
                        </div>
                          
                    </section>
                   
                    <!--policy_programs_section End-->
                    <!--policy_programs_section Start-->
                    <section id="policy_prgrms_section " class="common_spacing additional_topics">
                        <div class="flex_row">
                            <div class="col_12">
                                <h5>Additional Topics</h5>
                            </div>
                        </div>
                        <div class="flex_row">
                            <div class="col">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                        <h5>Project Reports</h5>
                                        <p>
                                        Developing Ecological Restoration Model In The Mine Spoils At Tetulmari Under Sijua Area (About 8-10 Ha) Of BCCL Mine, Forest Ecology & Environment Division Forest Research Institute, Dehradun, India
                                        </p>
                                        <a href="mining_knowledge_resources_project_reports_more.php">Read More</a>
                                        
                                    </div>
                                </div>
                            </div>
                            <!--Second Card-->
                            <div class="col">
                            <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                        <h5>Case studies</h5>
                                        <p>
                                        Comeopnedium of Best Practices on restoration of Mining Affected Areas
                                        </p>
                                        <a href="mining_knowledge_resources_case_studies_more.php">Read More</a>
                                        
                                    </div>
                                </div> 
                            </div>
                        </div>


                        <!--Second Row Start-->
                        <div class="flex_row secnd_row_top">
                            <div class="col">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/events.png" alt="">
                                    </div>
                                    <div class="events_card_content">
                                        <h5>Project Reports</h5>
                                        <p>
                                        Developing Ecological Restoration Model In The Mine Spoils At Tetulmari Under Sijua Area (About 8-10 Ha) Of BCCL Mine, Forest Ecology & Environment Division Forest Research Institute, Dehradun, India
                                        </p>
                                        <a href="mining_knowledge_resources_project_reports_more.php">Read More</a>
                                        
                                    </div>
                                </div>
                            </div>
                            <!--Second Card-->
                            <div class="col">
                            
                        </div>
                    </section>
                    <!--policy_programs_section End-->
                </div>
            </div>
        </div>
    </section>
    <!--First Section End -->
    <!--Second Section Start-->
</main>
    <!--Second Section End-->
    <!--Footer Section Start-->
    <?php include('includes/footer.php')?>
    <!-- Footer Section End-->