<?php include('includes/header.php')?>
 <!--Inner Banner Start-->
     <Section class="inner_banner ">
        <div class="container_fluid">
            <div class="flex_row">
                <div class="col_8">
                    <h4>Mining Affected Landscapes</h4>
                </div>
               
                <div class="col_4">
                    <ul class="new_breadcrumb">
                        <li><a href="<?php echo $base_url; ?>">Home</a></li>
                        <li>Mining Affected Landscapes</li>
                    </ul>
                </div>
            </div>
        </div>
    </Section>
    <!--Inner Banner End-->
    <!--First Section Start-->
    <section class="common_spacing">
        <div class="container_fluid">
            <div class="sidebar_sticky_wrapper">
                <div class="sidebar_sticky_left">
                    <ul class="vertical_tabs"> 
                        <li><a href="mining_affected_landscapes.php#CI_policy_progam" class="active"><span>Policy and Programs</span> <i class="icon-play"></i></a></li> 
                        <li><a href="mining_affected_landscapes.php#CI_knowledge_Resources"><span>Knowledge Resources</span> <i class="icon-play"></i></a></li>
                        <li><a href="mining_affected_landscapes.php#CI_design_framework"><span>Design Frameworks</span> <i class="icon-play"></i></a></li>
                        <li><a href="mining_affected_landscapes.php#CI_technology_tools"><span>Technology & Tools</span> <i class="icon-play"></i></a></li>
                    </ul>
                </div>

                <div class="sidebar_sticky_right">
                    <!-- Policy and Program start here -->
                    <div class="country_initiative_topic_wrapper" id="CI_policy_progam">
                        <div class="flex_row">
                            <div class="col_10">
                                 <h2>Knowledge Resources</h2>
                            </div>
                            <div class="col_2">
                            <button class="back_btn"><a href="mining_affected_landscapes.php#CI_knowledge_Resources" class="">Back</a></button>
                            </div>
                        </div>
                        <div class="flex_row">
                            <div class="col_12">
                            <h5>Training Materials </h5>
                            <p>
                                <STRONG>a.	Mine Reclamation: A handbook, Indian council of Forestry and Research Education</STRONG></br>
                                Minerals and mining sector contributes significantly to the economic growth and development of India in the form of exports, raw material to other industries in the country and finally vast employment opportunities and a high rate of wages. The Indian mining industry currently employs over 1.1 million people. Mining also yields foreign exchange and accounts for a significant portion of gross domestic product. Thus, the economic opportunities and wealth generated by mining for the country are substantial. However, mining is associated with severely adverse effects on the environment including loss of biodiversity, erosion, contamination of surface water, ground water, and soil. Mining causes physical destruction to the surrounding land by creating landscape blots such as open pits and piles of waste rock. Such disruptions result in the deterioration of the area's flora and fauna. In most of the cases the surface features and vegetation that were present before mining activities cannot be replaced after the process has ended. Loss of soil productivity, biological diversity, health and environmental hazards due to air, water and noise pollution microclimatic changes etc. are the major problems of the mining process. Reclamation on mined areas thus pose a great challenge for ecologists, biologists, agriculturists, engineers, soil scientist, and foresters as well who are invariably concerned about restoration of this disturbed ecosystem. Therefore, Indian Council of Forestry Research and Education has come up this operational manual incorporating comprehensive information on various aspects of mine reclamation including extent and causes of land degradation, scope and reclamation scenario in India, approaches and strategies of reclamation of mine spoils, essentials of ecofriendly mining and species prescriptions for different mining scenarios. The manual also contains outstanding reclamation efforts of various ICFRE institutions in recent past.                             
                             </p>
                                        <!--Pdf Section Start-->
                                        <div class="pdf_document">
                                            <a href="assets/pdf/book15.pdf.pdf" target="_blank">
                                                <img src="assets/images/pdf_icon.webp" class="pdf_icon">
                                                <span>book15.pdf</span>
                                            </a>
                                        </div>
                                        <!--Pdf Section End-->
                            </div>
                        </div>
                    </div>
                    <!-- Good Practice start here -->
                    <div class="country_initiative_topic_wrapper" id="additional_section">
                    <div class="flex_row">
                        <div class="col_12">
                        <h2>Additional Topics</h2>
                        </div>
                    </div>
                        <div class="flex_row">
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/Eco_Friendly_Approaches_for_Rehabilitation_of_Mine_Spoils_Institute_of_Forest_Genetics_and_Tree_Bre.webp" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Research Studies</h5>
                                        <p>
                                        Eco Friendly Approaches for Rehabilitation of Mine Spoils, Institute of Forest Genetics and Tree Breeding
                                        </p>
                                        <a href="mining_knowledge_resources_research_studies_more.php">Read More</a>
                                       
                                        
                                    </div>
                                </div>
                            </div>
                            <!--Second Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/compendium_of_Best_Practices_on_restoration_of_Mining_Affected_Areas.webp" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Case studies</h5>
                                        <p>
                                        Comeopnedium of Best Practices on restoration of Mining Affected Areas
                                        </p>
                                        <a href="mining_knowledge_resources_case_studies_more.php">Read More</a>
                                    </div>
                                </div>
                            </div>
                            <!--Third Card-->
                            <div class="col_6">
                                <div class="events_card">
                                    <div class="events_card_image">
                                        <img src="assets/images/events/Developing_Ecological_Restoration_Model_In_The_Mine_Spoils_At_Tetulmari_Under_Sijua_Area_About_8-10.webp" alt="">
                                    </div>
                                    <div class="events_card_content">
                                    <h5>Project Reports</h5>
                                        <p>
                                        Developing Ecological Restoration Model In The Mine Spoils At Tetulmari Under Sijua Area (About 8-10 Ha) Of BCCL Mine, Forest Ecology & Environment Division Forest Research Institute, Dehradun, India
                                        </p>
                                        <a href="mining_knowledge_resources_project_reports_more.php">Read More</a>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    


                    
                </div>
            </div>
        </div>
    </section>

     <!--First Section End-->
    <!--Footer Section Start-->
    <?php include('includes/footer.php')?>
    <!-- Footer Section End-->